# Generated by Django 4.2.2 on 2023-11-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualform',
            old_name='configuration',
            new_name='form_fields',
        ),
    ]
